apiVersion: v1
kind: Service
metadata:
  name: interactions-service
spec:
  selector:
    app: interactions-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interactions-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interactions-service
  template:
    metadata:
      labels:
        app: interactions-service
    spec:
      containers:
      - name: interactions-service
        image: yashwanthydg/interactions-service:v1 # Replace with your image
        ports:
        - containerPort: 8003
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DATABASE_URL
        readinessProbe:
          httpGet:
            path: /docs # FastAPI's docs endpoint
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /docs
            port: 8003
          initialDelaySeconds: 15
          periodSeconds: 20
