name: CI for Interactions Service

on:
  push:
    branches: [ main ]
    paths:
      - 'interactions-service/**'

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: ./interactions-service
        file: ./interactions-service/Dockerfile
        push: true
        tags: yashwanthydg/interactions-service:${{ github.sha }}
        # Example: goodberries/interactions-service:${{ github.sha }}
    
    - name: Update deployment manifest
        # ADDED: This step updates the image tag in your deployment file.
        # Assumes your file is located at 'kubernetes/deployment.yaml'.
      run: |
        sed -i "s|image: .*|image: yashwanthydg/interactions-service:${{ github.sha }}|g" kubernetes/manifest.yaml
  
    - name: Commit and push manifest changes
      # ADDED: This step commits the updated manifest file back to your main branch.
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add kubernetes/manifest.yaml
        git diff --staged --quiet || git commit -m "CI: Update image tag to ${{ github.sha }}"
        git push

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/interactions-service interactions-service=your-repo/interactions-service:${{ github.sha }} -n default
        # Example: kubectl set image deployment/interactions-service interactions-service=goodberries/interactions-service:${{ github.sha }} -n default

