name: CI for Interactions Service

on:
  push:
    branches: [ main ]
    paths:
      - 'interactions-service/**'

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: ./interactions-service
        file: ./interactions-service/Dockerfile
        push: true
        tags: yashwanthydg/interactions-service:${{ github.sha }}
        # Example: goodberries/interactions-service:${{ github.sha }}

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/interactions-service interactions-service=your-repo/interactions-service:${{ github.sha }} -n default
        # Example: kubectl set image deployment/interactions-service interactions-service=goodberries/interactions-service:${{ github.sha }} -n default

